<?php

include_once '../conf/config.inc.php'; // app config

if (!isset($TEMPLATE)) {
  $TITLE = 'About the Seismograms';
  $NAVIGATION = true;
  $HEAD = '<link rel="stylesheet" href="css/about.css" />';
  $FOOT = '';

  include 'template.inc.php';
}

?>

<h2>What is a Drum Recorder?</h2>

<figure class="right">
  <img src="img/heli_photo.jpg" alt="Photo of drum recorders" />
</figure>
<p>Drum recorders, like the ones pictured here, draw a seismogram on a piece of
  paper wrapped around a slowly revolving drum. As the drum revolves, the pen
  shifts across it, making a big spiral or helical record that eventually fills
  the entire page. When the paper is removed and laid flat, the record appears
  to be many horizontal lines, like lines in a book. These mechanical recorders,
  popular 30 years ago, have largely been replaced by computers, which digitize
  the data (typically at 100 samples per second) and store it in digital form.
  The digital data can then be displayed in a variety of ways by the computer.
  Here, we've displayed the data to look like the old-fashioned paper records
  that drum recorders produced. Pictured here are Helicorders&reg;, a common
  type of drum recorder, manufactured by Geotech Instruments, LLC.</p>

<h2>How to Read the Display</h2>

<figure class="right">
  <img src="img/typical.helicorder.gif" alt="typical helicorder" />
</figure>
<p>The seismograms displayed are from a few of the seismograph stations
  routinely recorded by the Northern California Seismograph Network. Each is a
  record of how the ground moved at a particular seismograph station in Northern
  California during a 24-hour period. The plots are "magnified" according to the
  level of background or ambient seismic noise, which is generated by wind,
  cultural disturbances and oceanic microseisms. Thus, some sites appear noisier
  than others. The seismogram is "read" like a book, from left to right and top
  to bottom (this is the direction that time increases). As with a book, the
  right end of any horizontal line "connects" with the left end of the line
  below it. Each line represents 15 minutes of data; four lines per hour. The
  colors of the horizontal lines have no particular significance; they are used
  to make it easier to distinguish lines from one another and to make it easier
  to recognize at which quarter-hour of data we are looking. The vertical lines
  are not part of the seismogram. They were added to indicate equal intervals of
  time. Time is indicated on the left in local Pacific time, and on the right
  end in Universal (or Greenwich) time.</p>

<h2>Interpretation</h2>

<p> When an earthquake occurs the seismogram will show ground motions that
  typically last from several tens of seconds to many minutes, depending on
  the size of the earthquake and the sensitivity of the seismograph. The height
  of the recorded waves on the seismogram (wave amplitude) is a greatly
  magnified representation of the actual ground motion. A recording of an
  earthquake has recognizable characteristics. Typically, one can recognize the
  arrival of different wave types: P (the fastest traveling waves), S (shear
  waves), and surface waves. On these seismograms you may see local earthquakes
  in Northern California and earthquakes elsewhere in the world.</p>
<p>Not all the wiggles seen on the seismograms are due to earthquakes.
  Anything that produces ground vibrations could be recorded, for example a car
  that passes by the seismometer (this is why we try to locate most of our
  seismometers well away from roads). Since the electrical signals from the
  seismometers are typically transmitted to the USGS by microwave or over
  telephone wires, electrical and radio noise on the transmission path may also
  show up on the seismogram. Such interference is usually easy to distinguish
  from earthquake-generated signals because it is often erratic or "spikey" in
  appearance.</p>
<p><a href="examples.php">Illustrative Examples</a> &raquo;</p>

<h2>How the Data Channels are Named</h2>
<p>Each data channel has a three part name such as MSL
  VHZ NC. The first part identifies the station. The middle part describes the
  data. The last part identifies the seismic network. The station name and network
  uniquely identify the location where the data are being recorded. The data descriptor
  tells a) what is being measured (velocity, displacement, acceleration), b) what
  sort of instrument is doing the recording (digital, hi-gain analog, etc.), and
  c) the orientation of the sensor (vertical, horizontal-north-south or
  horizontal-east-west). For example, VHZ is a <strong>high-gain</strong>
  (sensitive) analog <strong>velocity</strong> sensor,
  sensing<strong> vertical</strong> movement.</p>

<ul id="naming" class="no-style">
  <li>
    <h4>Station Name (Left)</h4>
    <ul class="no-style">
      <li>Examples: MSL, HSF, JSF, etc.</li>
    </ul>
  </li>
  <li>
    <h4>Data Type (Middle)</h4>
    <ul class="no-style">
      <li>V = Velocity<br />D = Displacement<br />A = Acceleration</li>
      <li>H = High Gain Analog<br />D = Digital</li>
      <li>Z = Vertical<br />N = North-South<br />E = East-West</li>
    </ul>
  </li>
  <li>
    <h4>Seismic Network (Right)</h4>
    <ul class="no-style">
      <li>NC = Northern California Seismic Network</li>
    </ul>
  </li>
</ul>
